version: '3.4'

services:
  node:
    build: 
      context: .
      dockerfile: Dockerfile
      target: node-builder
    user: "node"
    working_dir: /home/node/app
    environment:
      - "NODE_ENV=dev"
    command: bash -c "npm install && npm run start:dev"